name: Build

on:
  #workflow_dispatch
  push:
    branches: [ "master" ]
      
env:
  IMAGE_TAG: latest
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: msprg

jobs:
  build:
    name: Build and push appbackend
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: appbackend
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2.10
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          #archs: amd64, ppc64le, s390x, arm64
          dockerfiles: /DockerFiles/backend/Dockerfile
            
      - name: Push To docker.io
        id: push-to-docker
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
